name: Fetch all country cards with manual trigger

on:
  workflow_dispatch:
      inputs:
        chainType:
          description: 'Chain type'
          required: true
          default: 'testnet'

jobs:
  process_deposits:
    name: Run countries fetcher worker
    runs-on: ubuntu-latest
    env:
      MANAGER_PASSPHRASE: ${{ secrets.MANAGER_PASSPHRASE }}
      LEDGER_TYPE: ${{ github.event.inputs.chainType }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.9

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
          poetry-version: 1.1.6

    - name: Install python dependencies
      run: poetry install

    - uses: pre-commit/action@v3.0.0
      name: "Linters and formatters check"
      with:
        extra_args: --all-files --show-diff-on-failure

    - name: Update & fetch all cities
      run: |
        PYTHONPATH="." poetry run python src/countries/fetch_all.py

    - name: Commit files
      id: commit_files
      run: |
        git config --local user.email "millionalgos@pm.me"
        git config --local user.name "github-actions[bot]"
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "chore: reloaded all country cards ðŸ¤–" -a
          echo ::set-output name=has_commits::true
        else
          echo "no changes - skipping"
          echo ::set-output name=has_commits::false
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      if: steps.commit_files.outputs.has_commits == 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
